### ISSUE TITLE
touch.py Recent code breaking change in stmhal

### ISSUE THREAD

**Issue by peterhinch** [robert-hh/XPT2046-touch-pad-driver-for-PyBoard#3]
The constant stm.GPIO_BSRRL is now stm.GPIO_BSRR. This seems to have been done to make the name compatible with the device datasheet. Also affects TFT_IO.py.

**Comment by robert-hh** [comment]
The repository is updated now by replacing GPIO_BSRRL with GPIO_BSRR. I could have made that backward compatible, but one could also simply use the older version, if required.

**Comment by peterhinch** [comment]
OK, closing.
